/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.Color;

/**
 *
 * @author Jere
 */
public class PantAdminitrador extends javax.swing.JFrame {
    
    int xMouse, yMouse;
 

    /**
     * Creates new form PantAdminitrador
     */
    public PantAdminitrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        PanelFACTURAS = new javax.swing.JPanel();
        BotonFacturas = new javax.swing.JLabel();
        PanelVUELOS = new javax.swing.JPanel();
        VuelosBoton = new javax.swing.JLabel();
        PanelAVIONES = new javax.swing.JPanel();
        botonAviones = new javax.swing.JLabel();
        TextBoleto = new javax.swing.JLabel();
        TextReservar = new javax.swing.JLabel();
        TextMoficar = new javax.swing.JLabel();
        panelderelleno = new javax.swing.JPanel();
        HEADER = new javax.swing.JPanel();
        EXITPAN = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        PanelEMPLEADOS = new javax.swing.JPanel();
        BotonEmpleados = new javax.swing.JLabel();
        TextEMPLADOS = new javax.swing.JLabel();
        TextCLIENTES = new javax.swing.JLabel();
        PanelCLIENTES = new javax.swing.JPanel();
        BotonAviones = new javax.swing.JLabel();
        TextSUGERENCIAS = new javax.swing.JLabel();
        PanelRECLAMOSoSUGERENCIAS = new javax.swing.JPanel();
        BotonReclamosoSugerencias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colorescambiadoslogo (1).png"))); // NOI18N
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 170));

        titulo.setFont(new java.awt.Font("Agbalumo", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 153, 204));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("¡Bienvenid@! Admin"); // NOI18N
        BG.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 490, 80));

        PanelFACTURAS.setBackground(new java.awt.Color(153, 255, 255));
        PanelFACTURAS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotonFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Factura.png"))); // NOI18N
        BotonFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PanelFACTURASLayout = new javax.swing.GroupLayout(PanelFACTURAS);
        PanelFACTURAS.setLayout(PanelFACTURASLayout);
        PanelFACTURASLayout.setHorizontalGroup(
            PanelFACTURASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        PanelFACTURASLayout.setVerticalGroup(
            PanelFACTURASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );

        BG.add(PanelFACTURAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 170, 160));

        PanelVUELOS.setBackground(new java.awt.Color(0, 102, 255));
        PanelVUELOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        VuelosBoton.setBackground(new java.awt.Color(51, 102, 255));
        VuelosBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VuelosBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VUELOS.png"))); // NOI18N
        VuelosBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VuelosBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VuelosBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelVUELOSLayout = new javax.swing.GroupLayout(PanelVUELOS);
        PanelVUELOS.setLayout(PanelVUELOSLayout);
        PanelVUELOSLayout.setHorizontalGroup(
            PanelVUELOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VuelosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        PanelVUELOSLayout.setVerticalGroup(
            PanelVUELOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VuelosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        BG.add(PanelVUELOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        PanelAVIONES.setBackground(new java.awt.Color(51, 255, 255));
        PanelAVIONES.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonAviones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonAviones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/REAVION.png"))); // NOI18N
        botonAviones.setText("fvbdfb");
        botonAviones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAvionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelAVIONESLayout = new javax.swing.GroupLayout(PanelAVIONES);
        PanelAVIONES.setLayout(PanelAVIONESLayout);
        PanelAVIONESLayout.setHorizontalGroup(
            PanelAVIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 176, Short.MAX_VALUE)
        );
        PanelAVIONESLayout.setVerticalGroup(
            PanelAVIONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 166, Short.MAX_VALUE)
        );

        BG.add(PanelAVIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 180, 170));

        TextBoleto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto.setText("AVIONES");
        BG.add(TextBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

        TextReservar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextReservar.setForeground(new java.awt.Color(0, 153, 204));
        TextReservar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextReservar.setText("RESERVAS");
        BG.add(TextReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        TextMoficar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextMoficar.setForeground(new java.awt.Color(0, 153, 204));
        TextMoficar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextMoficar.setText("VUELOS");
        BG.add(TextMoficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        panelderelleno.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelderellenoLayout = new javax.swing.GroupLayout(panelderelleno);
        panelderelleno.setLayout(panelderellenoLayout);
        panelderellenoLayout.setHorizontalGroup(
            panelderellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        panelderellenoLayout.setVerticalGroup(
            panelderellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        BG.add(panelderelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1070, 20));

        HEADER.setBackground(new java.awt.Color(255, 255, 255));
        HEADER.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HEADERMouseDragged(evt);
            }
        });
        HEADER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HEADERMousePressed(evt);
            }
        });

        EXITPAN.setBackground(new java.awt.Color(255, 255, 255));

        X.setBackground(new java.awt.Color(255, 255, 255));
        X.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EXITPANLayout = new javax.swing.GroupLayout(EXITPAN);
        EXITPAN.setLayout(EXITPANLayout);
        EXITPANLayout.setHorizontalGroup(
            EXITPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        EXITPANLayout.setVerticalGroup(
            EXITPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(0, 1021, Short.MAX_VALUE)
                .addComponent(EXITPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EXITPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BG.add(HEADER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 30));

        PanelEMPLEADOS.setBackground(new java.awt.Color(0, 51, 255));
        PanelEMPLEADOS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotonEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        BotonEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEmpleadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelEMPLEADOSLayout = new javax.swing.GroupLayout(PanelEMPLEADOS);
        PanelEMPLEADOS.setLayout(PanelEMPLEADOSLayout);
        PanelEMPLEADOSLayout.setHorizontalGroup(
            PanelEMPLEADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        PanelEMPLEADOSLayout.setVerticalGroup(
            PanelEMPLEADOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        BG.add(PanelEMPLEADOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        TextEMPLADOS.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextEMPLADOS.setForeground(new java.awt.Color(0, 153, 204));
        TextEMPLADOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextEMPLADOS.setText("EMPLEADOS");
        BG.add(TextEMPLADOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, -1, -1));

        TextCLIENTES.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextCLIENTES.setForeground(new java.awt.Color(0, 153, 204));
        TextCLIENTES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextCLIENTES.setText("CLIENTES");
        BG.add(TextCLIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, -1, -1));

        PanelCLIENTES.setBackground(new java.awt.Color(51, 255, 255));
        PanelCLIENTES.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotonAviones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonAviones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        BotonAviones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAvionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelCLIENTESLayout = new javax.swing.GroupLayout(PanelCLIENTES);
        PanelCLIENTES.setLayout(PanelCLIENTESLayout);
        PanelCLIENTESLayout.setHorizontalGroup(
            PanelCLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonAviones, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        PanelCLIENTESLayout.setVerticalGroup(
            PanelCLIENTESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonAviones, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        BG.add(PanelCLIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        TextSUGERENCIAS.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextSUGERENCIAS.setForeground(new java.awt.Color(0, 153, 204));
        TextSUGERENCIAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextSUGERENCIAS.setText("RECLAMOS O SUGERENCIAS");
        BG.add(TextSUGERENCIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, -1, -1));

        PanelRECLAMOSoSUGERENCIAS.setBackground(new java.awt.Color(51, 102, 255));
        PanelRECLAMOSoSUGERENCIAS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotonReclamosoSugerencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonReclamosoSugerencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reclamososugerencias.png"))); // NOI18N
        BotonReclamosoSugerencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout PanelRECLAMOSoSUGERENCIASLayout = new javax.swing.GroupLayout(PanelRECLAMOSoSUGERENCIAS);
        PanelRECLAMOSoSUGERENCIAS.setLayout(PanelRECLAMOSoSUGERENCIASLayout);
        PanelRECLAMOSoSUGERENCIASLayout.setHorizontalGroup(
            PanelRECLAMOSoSUGERENCIASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonReclamosoSugerencias, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        PanelRECLAMOSoSUGERENCIASLayout.setVerticalGroup(
            PanelRECLAMOSoSUGERENCIASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonReclamosoSugerencias, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        BG.add(PanelRECLAMOSoSUGERENCIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    private void XMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseEntered
        EXITPAN.setBackground(Color.red);
        X.setForeground(Color.white);
    }//GEN-LAST:event_XMouseEntered

    private void XMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseExited
        EXITPAN.setBackground(Color.white);
        X.setForeground(Color.black);
    }//GEN-LAST:event_XMouseExited

    private void HEADERMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADERMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HEADERMouseDragged

    private void HEADERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADERMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HEADERMousePressed

    private void botonAvionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAvionesMouseClicked

        RegistroAvion RgA = new RegistroAvion ();
        RgA.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonAvionesMouseClicked

    private void VuelosBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VuelosBotonMouseClicked
      
        RegistroVuelos RgistroV = new RegistroVuelos();
        RgistroV.setVisible(true); 
        dispose();
      
    }//GEN-LAST:event_VuelosBotonMouseClicked

    private void BotonEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEmpleadosMouseClicked
        
        RegistroEmpleado RgistroE = new RegistroEmpleado();
        RgistroE.setVisible(true); 
        dispose();

        
    }//GEN-LAST:event_BotonEmpleadosMouseClicked

    private void BotonAvionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAvionesMouseClicked
        RegistroClientes RgistroC = new RegistroClientes();
        RgistroC.setVisible(true); 
        dispose();
    }//GEN-LAST:event_BotonAvionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantAdminitrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantAdminitrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantAdminitrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantAdminitrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantAdminitrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel BotonAviones;
    private javax.swing.JLabel BotonEmpleados;
    private javax.swing.JLabel BotonFacturas;
    private javax.swing.JLabel BotonReclamosoSugerencias;
    private javax.swing.JPanel EXITPAN;
    private javax.swing.JPanel HEADER;
    private javax.swing.JPanel PanelAVIONES;
    private javax.swing.JPanel PanelCLIENTES;
    private javax.swing.JPanel PanelEMPLEADOS;
    private javax.swing.JPanel PanelFACTURAS;
    private javax.swing.JPanel PanelRECLAMOSoSUGERENCIAS;
    private javax.swing.JPanel PanelVUELOS;
    private javax.swing.JLabel TextBoleto;
    private javax.swing.JLabel TextCLIENTES;
    private javax.swing.JLabel TextEMPLADOS;
    private javax.swing.JLabel TextMoficar;
    private javax.swing.JLabel TextReservar;
    private javax.swing.JLabel TextSUGERENCIAS;
    private javax.swing.JLabel VuelosBoton;
    private javax.swing.JLabel X;
    private javax.swing.JLabel botonAviones;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelderelleno;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
