package Vista;

import Controladores.ControldelLogin;
import static Controladores.ControldelLogin.LogiadoReser;
import java.awt.Color;

public class PantUsuario extends javax.swing.JFrame {

    int xMouse, yMouse;
    private int idClienteLogueado;
    private ControldelLogin controladorLogin;

    /**
     * Creates new form ModificarReserva
     */
    public PantUsuario() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        PanelBOLETO = new javax.swing.JPanel();
        imagenBoleto = new javax.swing.JLabel();
        TextBoleto = new javax.swing.JLabel();
        TextReservar = new javax.swing.JLabel();
        panelderelleno = new javax.swing.JPanel();
        HEADER = new javax.swing.JPanel();
        EXITPAN = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        PanelReserva1 = new javax.swing.JPanel();
        imagenReservar1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BotonReclamos = new javax.swing.JLabel();
        TextBoleto1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colorescambiadoslogo (1).png"))); // NOI18N
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 170));

        titulo.setFont(new java.awt.Font("Agbalumo", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 153, 204));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("¡Bienvenid@!"); // NOI18N
        BG.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 490, 80));

        PanelBOLETO.setBackground(new java.awt.Color(0, 204, 204));
        PanelBOLETO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        imagenBoleto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngwing.com (1).png"))); // NOI18N
        imagenBoleto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagenBoleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenBoletoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBOLETOLayout = new javax.swing.GroupLayout(PanelBOLETO);
        PanelBOLETO.setLayout(PanelBOLETOLayout);
        PanelBOLETOLayout.setHorizontalGroup(
            PanelBOLETOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        PanelBOLETOLayout.setVerticalGroup(
            PanelBOLETOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        BG.add(PanelBOLETO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        TextBoleto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto.setText("RECLAMOS");
        BG.add(TextBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        TextReservar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextReservar.setForeground(new java.awt.Color(0, 153, 204));
        TextReservar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextReservar.setText("RESERVAR");
        BG.add(TextReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        panelderelleno.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelderellenoLayout = new javax.swing.GroupLayout(panelderelleno);
        panelderelleno.setLayout(panelderellenoLayout);
        panelderellenoLayout.setHorizontalGroup(
            panelderellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        panelderellenoLayout.setVerticalGroup(
            panelderellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        BG.add(panelderelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 850, 20));

        HEADER.setBackground(new java.awt.Color(255, 255, 255));
        HEADER.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HEADERMouseDragged(evt);
            }
        });
        HEADER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HEADERMousePressed(evt);
            }
        });

        EXITPAN.setBackground(new java.awt.Color(255, 255, 255));

        X.setBackground(new java.awt.Color(255, 255, 255));
        X.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EXITPANLayout = new javax.swing.GroupLayout(EXITPAN);
        EXITPAN.setLayout(EXITPANLayout);
        EXITPANLayout.setHorizontalGroup(
            EXITPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        EXITPANLayout.setVerticalGroup(
            EXITPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(0, 801, Short.MAX_VALUE)
                .addComponent(EXITPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EXITPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BG.add(HEADER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        PanelReserva1.setBackground(new java.awt.Color(153, 255, 255));
        PanelReserva1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        imagenReservar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenReservar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/REAVION.png"))); // NOI18N
        imagenReservar1.setText("jLabel4");
        imagenReservar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagenReservar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenReservar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelReserva1Layout = new javax.swing.GroupLayout(PanelReserva1);
        PanelReserva1.setLayout(PanelReserva1Layout);
        PanelReserva1Layout.setHorizontalGroup(
            PanelReserva1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenReservar1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, Short.MAX_VALUE)
        );
        PanelReserva1Layout.setVerticalGroup(
            PanelReserva1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenReservar1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, Short.MAX_VALUE)
        );

        BG.add(PanelReserva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, 160));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        BotonReclamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonReclamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reclamososugerencias.png"))); // NOI18N
        BotonReclamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonReclamos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonReclamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonReclamosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonReclamos, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonReclamos, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 170, 160));

        TextBoleto1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto1.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto1.setText("MI BOLETO");
        BG.add(TextBoleto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    private void HEADERMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADERMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HEADERMouseDragged

    private void HEADERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADERMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HEADERMousePressed

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    private void XMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseEntered
        EXITPAN.setBackground(Color.red);
        X.setForeground(Color.white);
    }//GEN-LAST:event_XMouseEntered

    private void XMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseExited
        EXITPAN.setBackground(Color.white);
        X.setForeground(Color.black);
    }//GEN-LAST:event_XMouseExited

    private void BotonReclamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonReclamosMouseClicked
       
        QRusuario QRu = new QRusuario();
        QRu.setVisible(true);

        dispose();
        
    }//GEN-LAST:event_BotonReclamosMouseClicked

    private void imagenReservar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenReservar1MouseClicked

        PantaReservaCliente ReservaC = new PantaReservaCliente(LogiadoReser);
        ReservaC.setVisible(true);

        dispose();
    }//GEN-LAST:event_imagenReservar1MouseClicked

    private void imagenBoletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenBoletoMouseClicked
       
        Boleto PantBoleto = new Boleto();
        PantBoleto.setVisible(true);
        dispose();  
        
        
    }//GEN-LAST:event_imagenBoletoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Creamos una instancia del controlador de login
          // El controlador

                // Ahora pasamos el controlador a PantUsuario
                PantUsuario usuarioPantalla = new PantUsuario();
                usuarioPantalla.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JLabel BotonReclamos;
    private javax.swing.JPanel EXITPAN;
    private javax.swing.JPanel HEADER;
    private javax.swing.JPanel PanelBOLETO;
    private javax.swing.JPanel PanelReserva1;
    private javax.swing.JLabel TextBoleto;
    private javax.swing.JLabel TextBoleto1;
    private javax.swing.JLabel TextReservar;
    private javax.swing.JLabel X;
    private javax.swing.JLabel imagenBoleto;
    private javax.swing.JLabel imagenReservar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelderelleno;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
