/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controladores.conexionbasededatos;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import Modelo1.Reserva;
import Controladores.ControldelLogin;

import Controladores.ControladorReserva;
import Modelo1.BoletoModelo;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;

/**
 *
 * @author Jere
 */
public class PantaReservaCliente extends javax.swing.JFrame {

    int xMouse, yMouse;

    private ControladorReserva controlador;
    private Reserva reserv;
    private BoletoModelo boleto;
    

    public PantaReservaCliente(int idCliente) {
        initComponents();
       

        reserv = new Reserva();
        
        controlador = new ControladorReserva(reserv, this,idCliente);

        CargaropcionesOrigen();
        CargaropcionesDestino();
        CargaropcionesCategoria();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        panelderelleno = new javax.swing.JPanel();
        HEADER = new javax.swing.JPanel();
        EXITPAN = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        TextBoleto2 = new javax.swing.JLabel();
        TextBoleto3 = new javax.swing.JLabel();
        TextBoleto4 = new javax.swing.JLabel();
        TextBoleto5 = new javax.swing.JLabel();
        jButtonReserva = new javax.swing.JButton();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        TextBoleto6 = new javax.swing.JLabel();
        TextBoleto7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTVReserva = new javax.swing.JTable();
        jTextFieldnumerovuelo = new javax.swing.JTextField();
        jTextFieldPRECIO = new javax.swing.JTextField();
        jTextFieldHORA = new javax.swing.JTextField();
        CARGAR = new javax.swing.JButton();
        TextBoleto8 = new javax.swing.JLabel();
        jTextFieldILLA = new javax.swing.JTextField();
        TextBoleto9 = new javax.swing.JLabel();
        jlabelIdvuelo = new javax.swing.JLabel();
        TextBoleto10 = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colorescambiadoslogo (1).png"))); // NOI18N
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 160));

        titulo.setFont(new java.awt.Font("Agbalumo", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 153, 204));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Reserva De Vuelo"); // NOI18N
        BG.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 490, 80));

        panelderelleno.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelderellenoLayout = new javax.swing.GroupLayout(panelderelleno);
        panelderelleno.setLayout(panelderellenoLayout);
        panelderellenoLayout.setHorizontalGroup(
            panelderellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        panelderellenoLayout.setVerticalGroup(
            panelderellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        BG.add(panelderelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 850, 20));

        HEADER.setBackground(new java.awt.Color(255, 255, 255));
        HEADER.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HEADERMouseDragged(evt);
            }
        });
        HEADER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HEADERMousePressed(evt);
            }
        });

        EXITPAN.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EXITPANLayout = new javax.swing.GroupLayout(EXITPAN);
        EXITPAN.setLayout(EXITPANLayout);
        EXITPANLayout.setHorizontalGroup(
            EXITPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        EXITPANLayout.setVerticalGroup(
            EXITPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        X.setBackground(new java.awt.Color(0, 255, 51));
        X.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        X.setForeground(new java.awt.Color(0, 0, 255));
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("X");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(0, 984, Short.MAX_VALUE)
                .addGroup(HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EXITPAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EXITPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BG.add(HEADER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 30));

        TextBoleto2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto2.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto2.setText("ORGIEN");
        BG.add(TextBoleto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        TextBoleto3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto3.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto3.setText("ID VUELO");
        BG.add(TextBoleto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, -1, -1));

        TextBoleto4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto4.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto4.setText("CATEGORIA");
        BG.add(TextBoleto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        TextBoleto5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto5.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto5.setText("FECHA");
        BG.add(TextBoleto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        jButtonReserva.setBackground(new java.awt.Color(51, 204, 255));
        jButtonReserva.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonReserva.setText("RESERVAR");
        jButtonReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReservaMouseClicked(evt);
            }
        });
        jButtonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservaActionPerformed(evt);
            }
        });
        BG.add(jButtonReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 130, 40));

        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        BG.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 170, 30));

        jComboBoxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDestinoActionPerformed(evt);
            }
        });
        BG.add(jComboBoxDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 30));

        jComboBoxOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrigenActionPerformed(evt);
            }
        });
        BG.add(jComboBoxOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 170, 30));
        BG.add(jDateChooserFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 170, 30));

        TextBoleto6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto6.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto6.setText("PRECIO");
        BG.add(TextBoleto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        TextBoleto7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto7.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto7.setText("HORA");
        BG.add(TextBoleto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        JTVReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID VUELO", "NRO_VUELO", "ORIGEN", "DESTINO", "HORA", "PRECIO", "ASIENTOS DISPONIBLES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTVReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTVReservaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTVReserva);

        BG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 940, 170));

        jTextFieldnumerovuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumerovueloActionPerformed(evt);
            }
        });
        BG.add(jTextFieldnumerovuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 100, 30));

        jTextFieldPRECIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPRECIOActionPerformed(evt);
            }
        });
        BG.add(jTextFieldPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 150, 30));

        jTextFieldHORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHORAActionPerformed(evt);
            }
        });
        BG.add(jTextFieldHORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 100, 30));

        CARGAR.setBackground(new java.awt.Color(102, 255, 255));
        CARGAR.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CARGAR.setText("CARGAR");
        CARGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARGARActionPerformed(evt);
            }
        });
        BG.add(CARGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 120, 30));

        TextBoleto8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto8.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto8.setText("SILLA");
        BG.add(TextBoleto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        jTextFieldILLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldILLAActionPerformed(evt);
            }
        });
        BG.add(jTextFieldILLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 150, 30));

        TextBoleto9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto9.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto9.setText("DESTINO");
        BG.add(TextBoleto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jlabelIdvuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelIdvueloMouseClicked(evt);
            }
        });
        BG.add(jlabelIdvuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 100, 30));

        TextBoleto10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TextBoleto10.setForeground(new java.awt.Color(0, 153, 204));
        TextBoleto10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBoleto10.setText("NUM°VUELO");
        BG.add(TextBoleto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        SALIR.setBackground(new java.awt.Color(255, 51, 51));
        SALIR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("<");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        BG.add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    private void XMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseEntered
        EXITPAN.setBackground(Color.red);
        X.setForeground(Color.white);
    }//GEN-LAST:event_XMouseEntered

    private void XMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseExited
        EXITPAN.setBackground(Color.white);
        X.setForeground(Color.black);
    }//GEN-LAST:event_XMouseExited

    private void HEADERMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADERMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HEADERMouseDragged

    private void HEADERMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HEADERMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HEADERMousePressed

    private void jButtonReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReservaMouseClicked

    }//GEN-LAST:event_jButtonReservaMouseClicked

    private void jComboBoxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDestinoActionPerformed

    private void jComboBoxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOrigenActionPerformed

    private void JTVReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTVReservaMouseClicked
        try (Connection con = new conexionbasededatos().conectar()) {
            // Obtener la fila seleccionada en la tabla
            int fila = JTVReserva.getSelectedRow();
            String idVuelo = JTVReserva.getValueAt(fila, 0).toString();

            // Consulta para obtener los datos del vuelo, incluyendo los asientos disponibles y el precio
            String sql = "SELECT `IDVUELOS`,`NRO_VUELO`, `ORIGEN`, `DESTINO`, `FECHA`, `HORA`, `PRECIO`, `ASIENTO_DISPONIBLES` "
                    + "FROM `vuelos` WHERE `IDVUELOS` = ?";

            try (PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setString(1, idVuelo); // Establecer el parámetro del vuelo seleccionado

                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        // Rellenar los campos de la vista con los datos del vuelo
                        jlabelIdvuelo.setText(rs.getString("IDVUELOS"));
                        jTextFieldnumerovuelo.setText(rs.getString("NRO_VUELO"));  // Número de vuelo
                        jComboBoxOrigen.setSelectedItem(rs.getString("ORIGEN"));  // Origen
                        jComboBoxDestino.setSelectedItem(rs.getString("DESTINO"));  // Destino
                        jDateChooserFecha.setDate(rs.getDate("FECHA"));  // Fecha del vuelo
                        jTextFieldHORA.setText(rs.getString("HORA"));  // Hora del vuelo
                        jTextFieldPRECIO.setText(String.valueOf(rs.getInt("PRECIO")));

                        // Obtener la cantidad de asientos disponibles
                        int asientosDisponibles = rs.getInt("ASIENTO_DISPONIBLES");

                        // Si hay asientos disponibles, asignamos el siguiente asiento
                        if (asientosDisponibles > 0) {
                            int siguienteSilla = asientosDisponibles;
                            // Mostrar el número de asiento en un campo de texto de silla
                            jTextFieldILLA.setText("Silla " + siguienteSilla); // Mostrar número de asiento
                        }
                    }
                }
            }
        } catch (SQLException e) {
            // Si hay un error con la conexión o la consulta, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "ERROR AL CARGAR DATOS DEL VUELO: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_JTVReservaMouseClicked

    private void jTextFieldnumerovueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumerovueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumerovueloActionPerformed

    private void jTextFieldPRECIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPRECIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPRECIOActionPerformed

    private void jTextFieldHORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHORAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHORAActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jButtonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonReservaActionPerformed

    private void CARGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARGARActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        JTVReserva.setModel(modelo);  // Asegúrate de que JTVReserva es el JTable para mostrar vuelos

        // Consulta para obtener la información de los vuelos junto con los asientos disponibles y el precio
        String sql = "SELECT `IDVUELOS`, `NRO_VUELO`, `ORIGEN`, `DESTINO`, `FECHA`, `HORA`, `PRECIO`, `ASIENTO_DISPONIBLES` "
                + "FROM `vuelos`";

        try (Connection con = new conexionbasededatos().conectar(); PreparedStatement ps = con.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            // Agregar columnas a la tabla
            modelo.addColumn("ID VUELO");
            modelo.addColumn("NRO VUELO");
            modelo.addColumn("ORIGEN");
            modelo.addColumn("DESTINO");
            modelo.addColumn("FECHA");
            modelo.addColumn("HORA");
            modelo.addColumn("PRECIO");
            modelo.addColumn("ASIENTOS DISPONIBLES");

            // Recorrer los resultados y agregar filas a la tabla
            while (rs.next()) {
                Object[] fila = new Object[modelo.getColumnCount()];

                // Asignar valores a cada columna
                fila[0] = rs.getObject("IDVUELOS");
                fila[1] = rs.getObject("NRO_VUELO");
                fila[2] = rs.getObject("ORIGEN");
                fila[3] = rs.getObject("DESTINO");
                fila[4] = rs.getDate("FECHA");
                fila[5] = rs.getString("HORA");
                fila[6] = rs.getDouble("PRECIO"); // Cambié de `rs.getInt()` a `rs.getDouble()` por si el precio es decimal
                fila[7] = rs.getInt("ASIENTO_DISPONIBLES");  // Esto muestra la cantidad de asientos disponibles

                // Agregar la fila al modelo de la tabla
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            // Si hay un error con la consulta o la conexión, mostramos un mensaje de error
            JOptionPane.showMessageDialog(this, "ERROR AL CARGAR DATOS DE VUELOS: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CARGARActionPerformed

    private void jTextFieldILLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldILLAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldILLAActionPerformed

    private void jlabelIdvueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelIdvueloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlabelIdvueloMouseClicked

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
    PantUsuario PantallaUsuario = new PantUsuario();  // Pasa el controlador de login
    PantallaUsuario.setVisible(true);  // Muestra la ventana PantUsuario
    dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void CargaropcionesOrigen() {
        Connection con = new conexionbasededatos().conectar();
        Statement stmt = null;
        ResultSet rs = null;

        try {
            stmt = con.createStatement();

            // Consulta para obtener los valores del campo ENUM
            rs = stmt.executeQuery("SHOW COLUMNS FROM vuelos LIKE 'ORIGEN'");

            if (rs.next()) {
                String enumType = rs.getString("Type");
                enumType = enumType.replace("enum(", "").replace(")", "");
                String[] enumValues = enumType.split(",");

                jComboBoxOrigen.removeAllItems(); // Limpiar el JComboBox

                jComboBoxOrigen.addItem("ESCOGER");
                // Agregar los valores al JComboBox
                for (String value : enumValues) {
                    value = value.replace("'", "").trim(); // Limpiar comillas
                    jComboBoxOrigen.addItem(value);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR AL CARGAR TIPOS: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar recursos
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close(); // Cerrar la conexión aquí
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "ERROR AL CERRAR RECURSOS: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void CargaropcionesDestino() {
        Connection con = new conexionbasededatos().conectar();
        Statement stmt = null;
        ResultSet rs = null;

        try {
            stmt = con.createStatement();

            // Consulta para obtener los valores del campo ENUM
            rs = stmt.executeQuery("SHOW COLUMNS FROM vuelos LIKE 'DESTINO'");

            if (rs.next()) {
                String enumType = rs.getString("Type");
                enumType = enumType.replace("enum(", "").replace(")", "");
                String[] enumValues = enumType.split(",");

                jComboBoxDestino.removeAllItems(); // Limpiar el JComboBox

                jComboBoxDestino.addItem("ESCOGER");
                // Agregar los valores al JComboBox
                for (String value : enumValues) {
                    value = value.replace("'", "").trim(); // Limpiar comillas
                    jComboBoxDestino.addItem(value);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR AL CARGAR TIPOS: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar recursos
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close(); // Cerrar la conexión aquí
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "ERROR AL CERRAR RECURSOS: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void CargaropcionesCategoria() {
        Connection con = new conexionbasededatos().conectar();
        Statement stmt = null;
        ResultSet rs = null;

        try {
            stmt = con.createStatement();

            // Consulta para obtener los valores del campo ENUM
            rs = stmt.executeQuery("SHOW COLUMNS FROM reserva LIKE 'CATEGORIA'");

            if (rs.next()) {
                String enumType = rs.getString("Type");
                enumType = enumType.replace("enum(", "").replace(")", "");
                String[] enumValues = enumType.split(",");

                jComboBoxCategoria.removeAllItems(); // Limpiar el JComboBox

                jComboBoxCategoria.addItem("ESCOGER");
                // Agregar los valores al JComboBox
                for (String value : enumValues) {
                    value = value.replace("'", "").trim(); // Limpiar comillas
                    jComboBoxCategoria.addItem(value);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR AL CARGAR TIPOS: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar recursos
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (con != null) {
                    con.close(); // Cerrar la conexión aquí
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "ERROR AL CERRAR RECURSOS: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantaReservaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantaReservaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantaReservaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantaReservaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 // Obtener el ID del cliente logueado

                int idCliente = ControldelLogin.LogiadoReser;
                new PantaReservaCliente(idCliente).setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BG;
    private javax.swing.JButton CARGAR;
    private javax.swing.JPanel EXITPAN;
    private javax.swing.JPanel HEADER;
    public javax.swing.JTable JTVReserva;
    public javax.swing.JButton SALIR;
    private javax.swing.JLabel TextBoleto10;
    private javax.swing.JLabel TextBoleto2;
    private javax.swing.JLabel TextBoleto3;
    private javax.swing.JLabel TextBoleto4;
    private javax.swing.JLabel TextBoleto5;
    private javax.swing.JLabel TextBoleto6;
    private javax.swing.JLabel TextBoleto7;
    private javax.swing.JLabel TextBoleto8;
    private javax.swing.JLabel TextBoleto9;
    private javax.swing.JLabel X;
    public javax.swing.JButton jButtonReserva;
    public javax.swing.JComboBox<String> jComboBoxCategoria;
    public javax.swing.JComboBox<String> jComboBoxDestino;
    public javax.swing.JComboBox<String> jComboBoxOrigen;
    public com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextFieldHORA;
    public javax.swing.JTextField jTextFieldILLA;
    public javax.swing.JTextField jTextFieldPRECIO;
    public javax.swing.JTextField jTextFieldnumerovuelo;
    public javax.swing.JLabel jlabelIdvuelo;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelderelleno;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
